---
title: "Monte Carlo Simulation - 11 Bit Return Rate"
author: "Piotr Wieczorek"
date: "2023-10-07"
output: 
  html_document: 
    toc: yes
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
```

## Loading libraries

```{r}
library(tidyverse)
library(lubridate)
library(tseries)
```

## Loading and cleaning the data about 11 Bit daily return rates

```{r}
rm(list=ls())
```

```{r}
df <- read.csv('11b_d.csv')
```

```{r}
head(df)
```

```{r}
df <- df %>%
  select(c("Data","Zamkniecie")) %>%
  mutate(Data = lubridate::ymd(Data))
```

```{r}
colnames(df)
```
```{r}
colnames(df) <- c("Date","Close")
```

```{r}
head(df,10)
```

```{r}
df$return_rate <- (df$Close/lag(df$Close))-1
```

```{r}
df$return_rate <- round(df$return_rate,4)
```

```{r}
head(df,10)
```

## Exploring the data

### 11 Bit stock rate plot

```{r,fig.width=10}
df %>%
  ggplot(aes(x=Date,y=Close))+ 
  geom_line() + 
  scale_x_date(date_breaks = "2 months",date_labels = "%Y-%m-%d") + 
  labs(title="11 Bit Stock Rate") + 
  theme_bw()
```



### 11 Bit return rate plot

```{r,fig.width=10}
df %>%
  ggplot(aes(x=Date,y=return_rate))+ 
  geom_line() + 
  scale_x_date(date_breaks = "2 months",date_labels = "%Y-%m-%d") + 
  labs(title="11 Bit Return Rate") + 
  theme_bw()
```

### 11 Bit return rate density plot

```{r}
df %>%
  drop_na() %>%
  ggplot(aes(x=return_rate)) + 
  geom_density() + 
  labs(title="11 Bit Return Rate Density")+
  theme_bw()
```

### Stationarity test

```{r}
adf.test(df[-1,]$return_rate)
```

#### 11 Bit daily return rate is of stationary nature

```{r}
X = matrix(ncol = 30,nrow = 10000)
for(day in 1:30) {
  # for each day (30 in total) sample the return rate 100000 times
  for(i in 1:10000){
    X[i,day] = sample(df[-1,]$return_rate,1)
  }
}
```

## Daily Return Rate Simulation

```{r}
daily_return_rates <- apply(X,2,mean)
```

```{r}
daily_return_rates
```
```{r}
combined_return = 1  # start with 1, which means no return
for (r in daily_return_rates) {
   combined_return = combined_return * (1 + r)
}
```


### Cumulative return for a month

```{r}
total_month_return_rate = combined_return - 1
print(total_month_return_rate)
```



