---
title: "diabetes_classification"
author: "Piotr Wieczorek"
date: "2023-11-07"
output: 
  html_document: 
    theme: united
    toc_depth: 4
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message = FALSE)
```

## Libraries

```{r}
rm(list=ls())
```

```{r}
library(caret)
library(tidyverse)
library(hrbrthemes)
library(janitor)
library(naniar)
library(fastDummies)
```

## Reading and cleaning the data

```{r}
df <- read.csv('wine_data.csv')
```

```{r}
head(df)
```

### Unselecting uneccessary columns and changing variable types

```{r}
df <- df %>%
  select(-c(1,2)) %>%
  mutate(type = as.factor(type))


head(df)
```

```{r}
df <- df %>%
  mutate(quality = as.factor(quality))
```

### Descriptive statistics

```{r}
df %>%
  summarise(across(where(is.numeric),
                   list(mean = ~ round(mean(.),2),
                        median = ~ round(median(.),2),
                        sdev = ~ round(sd(.),2),
                        min = ~ round(min(.),2),
                        max = ~round(max(.),2)))) %>% 
  pivot_longer(cols = everything(),
               names_to = "Statistic",
               values_to = "Value") %>%
  separate(Statistic,
           c("Metric", "Statistic"),
           sep = "_") %>%
  pivot_wider(names_from = Statistic,
              values_from = Value)
```

```{r}
df %>%
  select_if(is.numeric) %>%
  colnames()
```


### Data distribution

```{r}
for (colname in df %>% select_if(is.numeric) %>% colnames()) {
  
  plot_density <- df %>%
    ggplot(aes(x=df[[colname]])) +
    geom_density() + 
    labs(title = paste("Density Plot of", str_to_sentence(colname)),
         x = colname) + 
    theme_ipsum()

print(plot_density)

  }
```

### Boxplots

```{r}
for (colname in df %>% select_if(is.numeric) %>% colnames()) {
  
  plot_boxplot <- df %>%
    ggplot(aes(x=df[[colname]])) +
    geom_boxplot() + 
    labs(title = paste("Boxplot of", str_to_sentence(colname)),
         x = colname) + 
    theme_ipsum()

print(plot_boxplot)

  }
```

## Modeling

### Data partition

```{r}
set.seed(123)

data_partition <- caret::createDataPartition(df$type,p=0.7, list = FALSE)

train_set <- df[data_partition,]
test_set <- df[-data_partition,]

print(dim(train_set))
print(dim(test_set))
print(nrow(train_set)/nrow(df))

```

### Dummy variables

```{r}
dummies_train <- fastDummies::dummy_cols(train_set[,-13],remove_selected_columns = TRUE,remove_first_dummy = TRUE)
dummies_test <- fastDummies::dummy_cols(test_set[,-13],remove_selected_columns = TRUE,remove_first_dummy = TRUE)

train_set <- cbind(dummies_train,train_set[,13])
```



```{r}
test_set <- cbind(dummies_test,test_set[,13])
```


```{r}
head(train_set)
```

```{r}
head(test_set)
```

```{r}
colnames(train_set)[18] <- "type"
colnames(test_set)[18] <- "type"
```

### First model

```{r}
log_mod <- glm(formula = type ~.,data=train_set, family="binomial")
print(summary(log_mod))
```
```{r}
prediction <- predict(log_mod,test_set,type="response")
```

```{r}
head(prediction)
```

```{r}
table(train_set$type)
```


```{r}
prediction_group <- ifelse(prediction >= 0.5, 'white', 'red')
```

#### Confusion matrix
```{r}
confusionMatrix(data = as.factor(prediction_group), reference = test_set$type,
    positive = "white")
```

### Second model (without 'quality' variable)

```{r}
log_mod_2 <- glm(formula = type ~. -quality_4 - quality_5 - quality_6 - quality_7 - quality_8 - quality_9 - pH -fixed.acidity,data=train_set, family="binomial")
print(summary(log_mod_2))
```

```{r}
prediction_2 <- predict(log_mod_2,test_set,type="response")
prediction_group_2 <- ifelse(prediction >= 0.5, 'white', 'red')
```

```{r}
head(prediction_group_2)
```
```{r}
head(prediction_2)
```

#### Confusion matrix

```{r}
confusionMatrix(data = as.factor(prediction_group_2), reference = test_set$type,
    positive = "white")
```










