---
title: "Using Loops to Optimize Code Regarding Creating Plots and Evaluating Statistical Measures"
author: "Piotr Wieczorek"
date: "2023-10-29"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message = FALSE)
```


```{r}
library(tidyverse)
library(scales)
library(moments)
```

```{r}
rm(list=ls())
```

```{r}
df <- iris
```

```{r}
head(df)
```
```{r}
colSums(is.na(df))
```
## Groupping numerical data by species

```{r}
th <- theme(title = element_text(size=16),
            axis.title.x = element_text(size=14),
            axis.title.y = element_text(size=14),
            axis.text.x = element_text(size=12),
            axis.text.y = element_text(size=12),
            legend.title = element_text(size=16),
            legend.text = element_text(size=14),
            strip.text = element_text(size = 16))
```


```{r}
df %>%
  group_by(Species) %>%
  summarise_at(c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"), list(mean = ~mean(.), median = ~median(.)))
```


```{r}
df_mean <- df %>%
    group_by(Species) %>%
    summarise_if(is.numeric, list(mean = ~mean(.))) %>%
    mutate(Species = str_to_title(Species))
```

```{r}
df_mean
```

## Plots

### Mean numerical variables' values based on species - bar plots

```{r,fig.width=12,fig.height=6}

  for (colname in c("Sepal.Length_mean", "Sepal.Width_mean","Petal.Length_mean","Petal.Width_mean")){
    
    plt2 <- df_mean %>%
    ggplot(aes(x=Species,y=.data[[colname]],fill=Species)) +
    scale_fill_manual(values  = c("#E18C7A","#649DAD","#64AD7C")) + 
    geom_bar(stat="identity") + 
    geom_text(aes(y=.data[[colname]],
                  label=.data[[colname]]),vjust=-0.25)+
    labs(title = paste(str_to_title(str_replace_all(colname,"[_.]"," ")), "by Species"),
         x = "Species",
         y= str_to_sentence(str_replace_all(colname,"[_.]"," "))) + 
    theme_bw() + th
    
  print(plt2)
    
    
  }
  
```

### Numerical variables' distribution plots based on Species

```{r,fig.width=14,fig.height=6}
for (colname in c("Sepal.Length","Sepal.Width","Petal.Length","Petal.Width")) {
  plt <- df %>%
  ggplot(aes(x=.data[[colname]],fill=Species)) + 
  geom_density(alpha=0.75) +
  scale_fill_manual(values  = c("#E18C7A","#649DAD","#64AD7C")) +
  facet_wrap(~Species,scales="free") +
  labs(title = paste(str_to_title(str_replace_all(colname,"[_.]"," ")), "by Species"),
       x = str_to_sentence(str_replace_all(colname,"[_.]"," "))) + 
  theme_bw() + th  
  
print(plt)
}
```

## Skewness, kurtosis, Shapiro-Wilk test

```{r}
df_dens <- data.frame()
for (colname in c("Sepal.Length","Sepal.Width","Petal.Length","Petal.Width")) {
  dens_skewness <- moments::skewness(df[[colname]])
  dens_kurtosis <- moments::kurtosis(df[[colname]])
  shapiro_test_p_val <- shapiro.test(df[[colname]])$p.value
  output <- cbind(colname,dens_skewness,dens_kurtosis,shapiro_test_p_val)
  df_dens <- rbind(df_dens,output)
}

df_dens %>%
  mutate(across(c(2:4),as.numeric)) %>%
  mutate_if(is.numeric,~round(.,4))
```







